### ISSUE TITLE
🧩 MVP component with database, without UI

### ISSUE THREAD

**Issue by felixcicatt** [Platform-Autorisatie-Beheer-Component/PABC-API#1]
NB: for inspiration, look at experiments done in https://github.com/PodiumD-Autorisatie-Beheer-Component/PABC-API/tree/experiment/PABC.Server

**As a ZAC developer**  
**I want** to supply functional roles via a REST API and receive a matrix with application roles and entity types  
**so that** I can handle authorization decisions.

**ACCEPTANCE CRITERIA**

- [ ] Required configuration is documented on the existing ReadTheDocs website  
- [ ] The API is deployed to the test environment using the Helm chart in the existing CI/CD pipeline  
- [ ] The API accepts a list of functional roles as input  
- [ ] The API returns, per entity type, a list of corresponding application roles
- [ ] The API endpoint is versioned
- [ ] If any functional roles are uknown in the API, it returns an error message
- [ ] The response adheres to the agreed format (JSON structure)  
- [ ] The database setup follows the agreed ERD  
- [ ] The seed data to be provided is used

**DETAILS**
- In this MVP, we do want a database connection but NO UI yet  
- In this MVP, we will populate / seed the database with predefined data  
- We are still expecting a list of the following data, which we will use to populate / seed the database at application startup:
  - Functional roles  
  - Application roles  
  - Domain(s)  
  - Entity types and which domain they belong to  
  - Mappings of functional role / domain / application role

Use the following OpenAPI schema:
```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "PABC.Server",
    "version": "1.0"
  },
  "paths": {
    "/api/v1/application-roles-per-entity-type": {
      "post": {
        "tags": [
          "GetApplicationRolesPerEntityType"
        ],
        "operationId": "Get application roles per entity type",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetApplicationRolesRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetApplicationRolesResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApplicationRoleModel": {
        "required": [
          "application",
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "application": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "EntityTypeModel": {
        "required": [
          "id",
          "type"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "GetApplicationRolesRequest": {
        "required": [
          "functionalRoleNames"
        ],
        "type": "object",
        "properties": {
          "functionalRoleNames": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": false
      },
      "GetApplicationRolesResponse": {
        "required": [
          "results"
        ],
        "type": "object",
        "properties": {
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GetApplicationRolesResponseModel"
            }
          }
        },
        "additionalProperties": false
      },
      "GetApplicationRolesResponseModel": {
        "required": [
          "applicationRoles",
          "entityType"
        ],
        "type": "object",
        "properties": {
          "entityType": {
            "$ref": "#/components/schemas/EntityTypeModel"
          },
          "applicationRoles": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ApplicationRoleModel"
            }
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

Use the following ERD:

![Image](https://github.com/user-attachments/assets/2b528334-94b7-42a5-9e4c-a04f4fdb3cf6)
